### ISSUE TITLE
Not compatible with Lightloader Build "1.12-SS-r7940C00-b5-5"

### ISSUE THREAD

**Issue by knniDE** [Minebench/ZoMBe#1]
Instandly crash on start

[20:43:33] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:43:33] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: bhz
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: bhz
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoSuchFieldError: init
	at de.minebench.zombe.liteloader.minecraft.transformers.MCStartTransformer.getInitMethod(MCStartTransformer.java:102) ~[mod-zombe-1.0.5-mc1.12.jar:?]
	at de.minebench.zombe.liteloader.minecraft.transformers.MCStartTransformer.transform(MCStartTransformer.java:40) ~[mod-zombe-1.0.5-mc1.12.jar:?]
	at de.minebench.zombe.core.minecraft.ZTransformer.transform(ZTransformer.java:15) ~[mod-zombe-1.0.5-mc1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more

**Comment by Phoenix616** [comment]
You are using an outdated version, the pre-release seems to work fine with build 8 of the 1.12 Liteloader.
